name: my-action
description: test of my actions

#variables
inputs:
  #Nombre de la variable, descripcion, es rquerida y un valor por defecto
  message:
    description: "value to print"
    required: true
    default: "Wazaaaaaaaa"

runs:
  #nos permite agrupar pasos comunes
  using: "composite"
  steps:
    - name: Saludo
      run: echo "Hola ${{inputs.message}}"
      shell: bash