#Nombre del Workflow
name: Hola Mundo

#Eventos
#se va a ejecutar cuando haga un push
on: 
  #se ejecutaran solo en esas ramas
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs: 
  
#Nombre del job
# Cada job se ejecuta dentro de un servidor
  hola:
    runs-on: ubuntu-latest
    steps: 
    - name: hola mundo
      run: echo "Hola Mundo"

    - name: generar archivo
      run: touch hola.txt
      
    - name: set Text
      run: echo "Hola Mundo texto" >> hola.txt
    
    - name: Read File
      run: cat hola.txt
    services: 
      mysql: 
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
      redis:
        image: redis
        ports:
          - 6379:6379
  
  respuesta:
    #nombre del job que esperara que termine de ejecutarse, y despues se ejecutara este
    needs: hola
    runs-on: ubuntu-latest
    #pasos
    steps: 
      #del mismo github actions
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: ls comando
      run: ls -al
  
  test-build:
    runs-on: ubuntu-latest
    steps: 
      #llamados actions, son acciones reutilizables
      #usamos este para posicionarnos y ejecutar el script.sh
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: test
      #con "|" podemos usar multilinea
        run: |
          chmod +x script.sh
          ./script.sh
      #ejecuta node js
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        #parametros al action de node js
        with:
          node-version: latest
      - name: nodeV
        run: node --version 

      - name: action
        uses: ./.github/actions/
        #pasamos un valor
        with: 
          message: "Haldor"
    
  variable:
    runs-on: ubuntu-latest
    #definimos una variable de entorno
    env:
      My_Var: Haldor Calderon
    steps:
      - name: saludo
      #Variable de steps
        env:
          My_var2: ", Como estas?"
          #usando una variable definida en la pagina de github
        run: echo "Hola $My_Var$My_var2 ${{vars.MY_VARIABLE}}"
            


