#Nombre del Workflow
name: Hola Mundo

#Eventos
#se va a ejecutar cuando haga un push
on: 
  #se ejecutaran solo en esas ramas
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs: 
#Nombre del job
# Cada job se ejecuta dentro de un servidor
  hola:
    runs-on: ubuntu-latest
    steps: 
    - name: hola mundo
      run: echo "Hola Mundo"

    - name: generar archivo
      run: touch hola.txt
      
    - name: set Text
      run: echo "Hola Mundo texto" >> hola.txt
    
    - name: Read File
      run: cat hola.txt
  
  respuesta:
    #nombre del job que esperara que termine de ejecutarse, y despues se ejecutara este
    needs: hola
    runs-on: ubuntu-latest
    #pasos
    steps: 
      #del mismo github actions
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: ls comando
      run: ls -al
  
  test-build:
    runs-on: ubuntu-latest
    steps: 
      - name: test
      #con "|" podemos usar multilinea
        run: |
          echo "hola Test" >> hola.txt
          cat hola.txt


