#Nombre del Workflow
name: Hola Mundo

#se va a ejecutar cuando haga un push
on: [push]

jobs: 
#Nombre del job
# Cada job se ejecuta dentro de un servidor
  hola:
    runs-on: ubuntu-latest
    steps: 
    - name: hola mundo
      run: echo "Hola Mundo"

    - name: generar archivo
      run: touch hola.txt
      
    - name: set Text
      run: echo "Hola Mundo texto" >> hola.txt
    
    - name: Read File
      run: cat hola.txt
  
  respuesta:
    #nombre del job que esperara que termine de ejecutarse, y despues se ejecutara este
    needs: hola
    runs-on: ubuntu-latest
    steps: 
    - name: ls comando
      run: ls -al